language: objective-c

xcode_workspace: iOS-Template.xcworkspace
xcode_scheme: Staging
osx_image: xcode7

before_install:
    - export LANG=en_US.UTF-8
    - sudo gem install cocoapods --no-document

install:
    - pod install

script:
    - ./iOS-Template/Scripts/build.sh
    - ./iOS-Template/Scripts/test.sh

notifications:
    hipchat:
        rooms:
            - $API_TOKEN@ios-base
    email:
        recipients:
            - juanpablo@fsstudio.com
            - matt@fsstudio.com
            # - other@example.com
        on_success: change # [always|never|change] # default: change
        on_failure: always # [always|never|change] # default: always
